# Generated by Django 3.0 on 2019-12-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='Contenu de la trame')),
            ],
            options={
                'verbose_name': 'Trame',
                'verbose_name_plural': 'Trames',
            },
        ),
    ]
