# Generated by Django 3.0 on 2019-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.CharField(max_length=128, verbose_name='Depth')),
                ('offset', models.CharField(max_length=128, verbose_name='Offset')),
                ('checksum', models.CharField(max_length=128, verbose_name='Checksum')),
                ('content', models.CharField(max_length=128, verbose_name='Trame content')),
            ],
            options={
                'verbose_name': 'DPT - Depth of Water data',
                'verbose_name_plural': 'DPT - Depth of Water data',
            },
        ),
        migrations.CreateModel(
            name='DataRMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc', models.TimeField(verbose_name='UTC')),
                ('status', models.CharField(max_length=1, verbose_name='Status')),
                ('latitude', models.CharField(max_length=128, verbose_name='Latitude')),
                ('NorS', models.CharField(max_length=1, verbose_name='N or S')),
                ('longitude', models.CharField(max_length=128, verbose_name='Longitude')),
                ('EorW', models.CharField(max_length=1, verbose_name='E or W')),
                ('speed', models.CharField(max_length=128, verbose_name='Speed over ground, knots')),
                ('track', models.CharField(max_length=128, verbose_name='Track made good, degrees true')),
                ('date', models.CharField(max_length=128, verbose_name='Date')),
                ('magnetic', models.CharField(max_length=128, verbose_name='Magnetic Variation, degrees')),
                ('EorWm', models.CharField(max_length=1, verbose_name='E or W')),
                ('checksum', models.CharField(max_length=128, verbose_name='Checksum')),
                ('content', models.CharField(max_length=128, verbose_name='Trame content')),
            ],
            options={
                'verbose_name': 'RMC - Recommended Minimum Navigation Information data',
                'verbose_name_plural': 'RMC - Recommended Minimum Navigation Information data',
            },
        ),
        migrations.CreateModel(
            name='Trame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='Trame content')),
            ],
            options={
                'verbose_name': 'Trame',
                'verbose_name_plural': 'Trames',
            },
        ),
    ]
