- name: Installation du serveur de dev
  hosts: localhost

  tasks:

  - name: Update the system
    yum:
      name: "*"
      state: latest
      
  - name: Ensure some packages are present
    yum:
      name: git.x86_64, python3.x86_64, gcc.x86_64, docker.x86_64, epel-release.noarch
      state: present      
      
  - name: Disable SELinux
    selinux:
      state: disabled
      
  - name: Disable firewalld.service
    systemd: name=firewalld enabled=no
     
  - name: Stop firewalld.service
    systemd: name=firewalld state=stopped

  - name: Start docker.service
    systemd: name=docker state=started
    
  - name: Enable docker.service
    systemd: name=docker enabled=yes
    
  - name: Install virtualenv package
    pip: 
      name: virtualenv    
      executable: pip3
      
  - name: Install virtualenv package
    pip: 
      name: docker-compose    
      executable: pip3